export const actionTypes = {
	SET_USER: 'SET_USER',
	SET_USERS_LOGGED: 'SET_USERS_LOGGED',
	SELECT_USER_CHAT: 'SELECT_USER_CHAT',
	GET_COUNTRIES: 'GET_COUNTRIES',
	SET_COUNTRIES: 'SET_COUNTRIES',
	SET_SELECTED_COUNTRY: 'SET_SELECTED_COUNTRY',
	SET_MESSAGE: 'SET_MESSAGE',
};
